# Numpy - Numerical Python

## 1. Numpy Array

### List와 넘파이 어레이 속도 비교

In [1]:
import numpy as np
np_arr = np.arange(100000)

In [2]:
nu_list = []
for i in range(100000):
    nu_list.append(i)

In [3]:
nu_list = [i for i in range(100000)]

In [4]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 214 ms


In [5]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 8 ms


### 1차원 배열(array) 만들기

In [6]:
vector = np.array([1, 4, 7, 10], float)
vector

array([ 1.,  4.,  7., 10.])

In [7]:
type(vector)

numpy.ndarray

In [8]:
vector.shape

(4,)

### 2차원 배열 만들기

In [9]:
matrix = np.array([[1,2,5,8], [2,3,4,9], [4,5,6,7]])
matrix

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [10]:
matrix.shape

(3, 4)

### 3차원 배열 만들기

In [11]:
t_list = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
tensor = np.array(t_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [12]:
tensor.shape

(4, 3, 4)

## Array shape

### ndim & size (몇차원이냐? 엘리먼트 갯수가 몇개냐?)

In [13]:
vector.ndim, matrix.ndim, tensor.ndim

(1, 2, 3)

In [14]:
vector.size, matrix.size, tensor.size

(4, 12, 48)

### dtype

In [15]:
a = np.array([[1, 2, 3], [4.5, '5', '6']], dtype=np.float32)
a

array([[1. , 2. , 3. ],
       [4.5, 5. , 6. ]], dtype=float32)

In [16]:
a.nbytes

24

In [17]:
vector.nbytes

32

### Reshape

In [19]:
test_matrix = np.array([[1,2,3,4], [5,6,7,8]])
test_matrix.shape

(2, 4)

In [20]:
test_matrix.reshape(8,)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
test_matrix.reshape(2,2,2)

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
test_matrix.reshape(-1,2)   # test_matrix.reshape(4,2)와 동일

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [23]:
test_matrix.reshape(2,-1,2)   # test_matrix.reshape(2,2,2)와 동일

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### flatten (다차원 -> 1차원)

In [24]:
test_matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])