# Numpy - Numerical Python

## 1. Numpy Array

### List와 넘파이 어레이 속도 비교

In [1]:
import numpy as np
np_arr = np.arange(100000)

In [2]:
nu_list = []
for i in range(100000):
    nu_list.append(i)

In [3]:
nu_list = [i for i in range(100000)]

In [4]:
%%time
for i in range(100):
    sum(nu_list)

Wall time: 185 ms


In [5]:
%%time
for i in range(100):
    np.sum(np_arr)

Wall time: 6 ms


### 1차원 배열(array) 만들기

In [6]:
vector = np.array([1, 4, 7, 10], float)
vector

array([ 1.,  4.,  7., 10.])

In [7]:
type(vector)

numpy.ndarray

In [8]:
vector.shape

(4,)

### 2차원 배열 만들기

In [9]:
matrix = np.array([[1,2,5,8], [2,3,4,9], [4,5,6,7]])
matrix

array([[1, 2, 5, 8],
       [2, 3, 4, 9],
       [4, 5, 6, 7]])

In [10]:
matrix.shape

(3, 4)

### 3차원 배열 만들기

In [12]:
t_list = [[[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]],
          [[1,2,5,8], [2,3,4,9], [4,5,6,7]]]
tensor = np.array(t_list)
tensor

array([[[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]],

       [[1, 2, 5, 8],
        [2, 3, 4, 9],
        [4, 5, 6, 7]]])

In [13]:
tensor.shape

(4, 3, 4)

## Array shape

### ndim & size

In [14]:
vector.ndim, matrix.ndim, tensor.ndim

(1, 2, 3)