## Numpy Creation

### arange

In [2]:
import numpy as np
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [5]:
list(range(0, 5, 0.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(0, 5, 0.5).tolist()

[0.0, 0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5]

In [7]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### ones, zeros and empty

In [8]:
np.zeros(shape=(10,), dtype=np.int8)	# 원소가 10개인 벡터 생성

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [9]:
np.ones((2, 5))	    # 2 x 5 – 값이 1인 matrix 생성

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
np.empty((3, 5))	# 메모리가 초기화되어 있지 않음

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Something like

In [11]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [12]:
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [13]:
np.empty_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

### Identity(단위 행렬)

In [14]:
np.identity(n=3, dtype=np.int32)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### eye (대각선이 1인 행렬)

In [16]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.eye(3, 5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

### diag (대각 행렬의 값을 추출)

In [20]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [21]:
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
np.diag(matrix, k=1)

array([1, 5])

### Random sampling

In [23]:
np.random.seed(2021)

In [24]:
np.random.uniform(0, 1, 10).reshape(2,5)	# 균등 분포	(최소, 최대, 개수)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [25]:
np.random.normal(0, 1, 10).reshape(2,5)	# 정규 분포 (평균, 표준편차, 개수)

array([[ 0.10641374,  0.42215483,  0.12420684, -0.83795346,  0.4090157 ],
       [ 0.10275122, -1.90772239,  1.1002243 , -1.40232506, -0.22508127]])